version: '3'
services: 
    ms-sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        environment: 
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "CoreLogicProjectSQL5267"
        ports: 
            - "1433:1433"
        volumes: 
            - db-data:/var/opt/mssql/data
    dotnetlibrary:
        build: .
        environment: 
            DBServer: "ms-sql-server"
            DBUser: "sa"
            DBPassword: "CoreLogicProjectSQL5267"
            DBCatalog: "LibraryDB"
            DBMigrate: "y"
        ports:
            - "8080:80"
volumes: 
    db-data: